name: Deploy Node.js App to cPanel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.BACKEND__CPANEL_HOST }}
          username: ${{ secrets.BACKEND__CPANEL_USERNAME }}
          password: ${{ secrets.BACKEND__CPANEL_PASSWORD }}
          port: 21
          local-dir: Backend/
          server-dir: /
